var hero = {
    name:"Farva",
    level:5,
    type:"Undead Knight",
    accuracy: 10,
    strength: 7,
    toughness: 6,
    speed: 7,
    luck: 10,
    weapon: ['Bone Scabre', 7, 12],
    skillPointsCurrent:1,
    skillPoints:20,
    hitPointsCurrent:20,
    hitPoints:20,
    skills:['Finish Him','Light on your toes'],
};

var zombieBob = {
    name:"Farmer Bob Brains",
    level:8,
    type:"Zombie Botanist",
    accuracy: 6,
    strength: 7,
    toughness: 7,
    speed: 3,
    luck: 1,
    weapon: ['Pitch Fork', 5, 15],
    skillPointsCurrent:10,
    skillPoints:10,
    hitPointsCurrent:1,
    hitPoints:18,
    skills:['Bite','Skewer!'],
};

var rockMonster = {
    name:"Rock Monster",
    level:10,
    type:"Rocking and Rolling",
    accuracy: 4,
    strength: 10,
    toughness: 10,
    speed: 3,
    luck: 4,
    weapon: ['Fists', 10, 13],
    skillPointsCurrent:4,
    skillPoints:4,
    hitPointsCurrent:30,
    hitPoints:30,
    skills:['Crush','Pound'],
};